### ISSUE TITLE
Flask curve and surface fitter

### ISSUE THREAD

**Issue by zunzun** [miyamot0/PythonDiscountingApp#1]
My Flask-based curve and surface fitting application is on github at

https://github.com/zunzun/FlaskFit

The graphs for curve fitting plot the 95% confidence intervals, so you might be interested in using that part of the code.  I personally think the 3D surface plots look cool.  E-mail me at zunzun@zunzun.com, I would be glad to help you with the code or answer any technical questions.

**Comment by miyamot0** [comment]
Ah, this is very interesting.  I will give a look.

The project is pretty much on hiatus until I can move beyond approximate
Bayesian model selection to full Bayesian approaches.

Thanks for the graphing tip!

-SG

Shawn P. Gilroy, PhD BCBA NCSP
Marie Skłodowska Curie Research Scientist
ASSISTID Fellow
National University of Ireland, Galway
shawn.gilroy@nuigalway.ie

Source Code/Projects:
https://github.com/miyamot0
http://www.smallnstats.com
